[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[programs.localnet]
mpl_auction_house="hausS13jsjafwWwGqZTUQRmWyvyxn9EQpqMwV1PBBmk"

[programs.devnet]
mpl_auction="6Z6TYHgKq9jW8ZMCgnU8yymzm6aQaXvv1aEzMMZoNWks"
mpl_metaplex="GKgWgEvYV43UuDTJQ71QxUZK3kKqMHbG5PNaPRx1deBe"
mpl_token_metadata="12qTEpUSy7utaVFRTjEEZYzHgCkThgVgH4xhunJCtuE1"
mpl_token_vault="HhKCYuYr4zMuGbdvscZeEEM4X6oF8dzQgtrm1N6hmsUb"
mpl_nft_packs="6jgXfPmxLBGSKHnkfVfEwC2t9mYr95dLXHBHLUmNdhy5"

[[test.genesis]]
address = "6Z6TYHgKq9jW8ZMCgnU8yymzm6aQaXvv1aEzMMZoNWks"
program = "target/deploy/mpl_auction.so"

[[test.genesis]]
address = "GKgWgEvYV43UuDTJQ71QxUZK3kKqMHbG5PNaPRx1deBe"
program = "target/deploy/mpl_metaplex.so"

[[test.genesis]]
address = "12qTEpUSy7utaVFRTjEEZYzHgCkThgVgH4xhunJCtuE1"
program = "target/deploy/mpl_token_metadata.so"

[[test.genesis]]
address = "HhKCYuYr4zMuGbdvscZeEEM4X6oF8dzQgtrm1N6hmsUb"
program = "target/deploy/mpl_token_vault.so"

[workspace]
members = [
  "auction/program",
  "metaplex/program",
  "nft-packs/program",
  "token-metadata/program",
  "token-vault/program"
] 
